name: Release
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types: 
      - completed
jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Build
        shell: bash
        run: |
          dotnet publish src/App/App.csproj --framework netcoreapp3.1 --runtime "linux-x64" -c Release -o "linux-release"
            7z a -tzip "linux-release.zip" "./linux-release/*"
          rm -r "linux-release"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}