name: Release
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

  push:
    tags:
    - "v*.*.*"
    branches: [main]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    env:
      DOTNET_ROOT: /home/runner/.dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build for Linux
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_linux="Chirp-$tag-linux-x64"

          cd "src/Chirp.CLI.Client"

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "$release_name_linux" /p:PublishTrimmed=true /p:PublishSingleFile=true

          7z a -tzip "${{ github.workspace }}/src/Chirp.CLI.Client/${release_name_linux}.zip" "./${release_name_linux}/*"

          rm -r "${release_name_linux}"

      - name: Set Tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Publish for Linux
        uses: softprops/action-gh-release@v1
        with:
          files:  |
           ${{ github.workspace }}/src/Chirp.CLI.Client/Chirp-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-macos:
    runs-on: ubuntu-latest
    env:
      DOTNET_ROOT: /home/runner/.dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build for macOS
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_macos="Chirp-$tag-macos-x64"

          cd "src/Chirp.CLI.Client"

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "$release_name_macos" /p:PublishTrimmed=true /p:PublishSingleFile=true

          7z a -tzip "${{ github.workspace }}/src/Chirp.CLI.Client/${release_name_macos}.zip" "./${release_name_macos}/*"

          rm -r "${release_name_macos}"

      - name: Set Tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Publish for macOS
        uses: softprops/action-gh-release@v1
        with:
          files:  |
            ${{ github.workspace }}/src/Chirp.CLI.Client/Chirp-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  release-windows:
    runs-on: ubuntu-latest
    env:
      DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build for Windows
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_windows="Chirp-$tag-win-x64"

          cd "src/Chirp.CLI.Client"

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "win-x64" -c Release -o "$release_name_windows"  /p:PublishTrimmed=true /p:PublishSingleFile=true

          7z a -tzip "${{ github.workspace }}/src/Chirp.CLI.Client/${release_name_windows}.zip" "./${release_name_windows}/*" 

          rm -r "${release_name_windows}"
          
      - name: Set Tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Publish for Windows
        uses: softprops/action-gh-release@v1
        with:
          files:  |
           ${{ github.workspace }}/src/Chirp.CLI.Client/Chirp-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}