name: Release
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed
  push:
    tags:
    - "v*.*.*"
    branches: [main]
jobs:
  tests: 
    uses: ./.github/workflows/build_and_test.yml
  release:
    needs: ["tests"]
    runs-on: ubuntu-latest
    env:
      DOTNET_ROOT: /home/runner/.dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*
      - name: Builds release
        shell: bash
        run: |
          for release in linux-x64 macos-x64 win-x64
          tag=$(git describe --tags --abbrev=0)
          do
            echo Chirp-$tag-$release
          cd "Chirp.Razor"
          dotnet publish Chirp.Razor.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "release" /p:PublishTrimmed=true /p:PublishSingleFile=true
          7z a -tzip "${{ github.workspace }}/Chirp.Razor/${release}.zip" "./${release}/*"
          rm -r "${release}"
          done
      - name: Set Tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files:  |
           ${{ github.workspace }}/Chirp.Razor/Chirp-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}