name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_windows="App-$tag-win-x64"  

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "win-x64" -c Release -o "$release_name_windows"

            7z a -tzip "${release_name_windows}.zip" "./${release_name_windows}/*"  

          rm -r "${release_name_windows}"

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_windows="App-$tag-win-x64"  

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "$release_name_macos"

            7z a -tzip "${release_name_macos}.zip" "./${release_name_macos}/*"

          rm -r "${release_name_macos}"
        

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_linux="App-$tag-linux-x64"

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "$release_name_linux"

            7z a -tzip "${release_name_linux}.zip" "./${release_name_linux}/*"

          rm -r "${release_name_linux}"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
          tag_name: SOMENEWTAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}