name: Release
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      # Build for Linux
      - name: Build for Linux
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_linux="App-$tag-linux-x64"

          cd "src/Chirp.CLI.Client"

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "$release_name_linux"

          7z a -tzip "${release_name_linux}.zip" "./${release_name_linux}/*"

          rm -r "${release_name_linux}"

      # Build for macOS
      - name: Build for macOS
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_macos="App-$tag-osx-x64"

          cd "src/Chirp.CLI.Client"

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "$release_name_macos"

          7z a -tzip "${release_name_macos}.zip" "./${release_name_macos}/*"

          rm -r "${release_name_macos}"

      # Build for Windows
      - name: Build for Windows
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_windows="App-$tag-win-x64"

          cd "src/Chirp.CLI.Client"

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "win-x64" -c Release -o "$release_name_windows"

          7z a -tzip "${release_name_windows}.zip" "./${release_name_windows}/*"

          rm -r "${release_name_windows}"

      # Publish for all platforms
      - name: Publish for Linux
        uses: softprops/action-gh-release@v1
        with:
          files: "App-*linux-x64.zip"
          tag_name: "v1.1.17"  # Specify your tag explicitly here this has to be changed so it is automatically done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish for macOS
        uses: softprops/action-gh-release@v1
        with:
          files: "App-*osx-x64.zip"
          tag_name: "v1.1.17"  # Specify your tag explicitly here this has to be changed so it is automatically done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish for Windows
        uses: softprops/action-gh-release@v1
        with:
          files: "App-*win-x64.zip"
          tag_name: "v1.1.17"  # Specify your tag explicitly here this has to be changed so it is automatically done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
