name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-linux-x64"

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "$release_name"
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          rm -r "${release_name}"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
          tag_name: $tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}