name: Release
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types: 
     - completed

  push:
    branches: [ main ]
jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_linux="App-$tag-linux-x64"

          cd ../../src/Chirp.CLI.Client

          dotnet publish Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "$release_name_linux"

            7z a -tzip "${release_name_linux}.zip" "./${release_name_linux}/*"

          rm -r "${release_name_linux}"
          

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
          tag_name: ${{ steps.build.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}